#!/usr/bin/env node
import { resolve, join } from "node:path";
import {
  copyFileSync,
  mkdirSync,
  writeFileSync,
  chmodSync,
  existsSync,
} from "node:fs";
import { homedir } from "node:os";
import { startServer } from "./server.js";
import { SessionStore } from "./store.js";
import { attachWebSocket } from "./ws.js";
import { registerEntry, unregister, type RegistryEntry } from "./registry.js";
import { readProjectConfig } from "./project-config.js";

// Bundled by esbuild — declared at build time. See build.mjs.
declare const __PINTA_VERSION__: string;
// CommonJS module dir — esbuild's `format: cjs` output provides this natively;
// declared here so the TS source typechecks. Points at the published `dist/`,
// where build.mjs vendors the skill files under `dist/skill/`.
declare const __dirname: string;
const VERSION = typeof __PINTA_VERSION__ === "string" ? __PINTA_VERSION__ : "dev";

type Args = {
  projectRoot: string;
  port: number;
  /** True if --port was explicitly passed; disables auto-allocation. */
  portExplicit: boolean;
  verbose: boolean;
};

function parseArgs(argv: string[]): Args {
  const args: Args = {
    projectRoot: process.cwd(),
    port: 7878,
    portExplicit: false,
    verbose: false,
  };

  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--project" || a === "-p") {
      args.projectRoot = resolve(argv[++i] ?? process.cwd());
    } else if (a === "--port") {
      args.port = Number(argv[++i] ?? args.port);
      args.portExplicit = true;
    } else if (a === "--verbose" || a === "-v") {
      args.verbose = true;
    } else if (a === "--help" || a === "-h") {
      printHelp();
      process.exit(0);
    } else if (!a?.startsWith("-")) {
      // positional shorthand: first positional = projectRoot
      args.projectRoot = resolve(a!);
    }
  }
  return args;
}

function printHelp(): void {
  process.stdout.write(
    [
      "pinta-companion — annotation hub for the Pinta extension",
      "",
      "Usage:",
      "  pinta-companion [--project <path>] [--port 7878] [--verbose]",
      "  pinta-companion <project_path>",
      "  pinta-companion install-skill        install the /pinta Claude Code skill",
      "",
      "Defaults:",
      "  --project  cwd",
      "  --port     7878 (auto-increments to 7898 if busy when not pinned)",
      "",
    ].join("\n"),
  );
}

// The start-companion.js the installer drops into ~/.claude/skills/pinta/.
// Unlike the repo's scripts/install-skill.sh (which hardcodes a path to the
// cloned companion), the npm flavor launches the *published* companion via
// npx, so it works with zero checkout. SKILL.md's discovery also reads this
// location, so the file stays for parity even though `npx pinta-companion .`
// is the documented start command.
const START_COMPANION_NPX = `#!/usr/bin/env node
// Auto-generated by \`pinta-companion install-skill\`. Starts the published
// companion via npx — no repo checkout needed. Regenerated on reinstall.
import { spawn } from "node:child_process";
import { resolve } from "node:path";

const projectRoot = resolve(process.argv[2] ?? process.cwd());
const npx = process.platform === "win32" ? "npx.cmd" : "npx";
const child = spawn(npx, ["-y", "pinta-companion", projectRoot], {
  stdio: "inherit",
});
child.on("exit", (code) => process.exit(code ?? 0));
`;

/**
 * `pinta-companion install-skill` — copy the vendored skill files into
 * ~/.claude/skills/pinta/ so `/pinta` works without cloning the repo. Mirrors
 * scripts/install-skill.sh, but sources the files bundled in this package and
 * writes an npx-based start helper instead of a repo-path one. Idempotent.
 */
function installSkill(): void {
  const skillSrc = join(__dirname, "skill");
  const skillMd = join(skillSrc, "SKILL.md");
  if (!existsSync(skillMd)) {
    process.stderr.write(
      `[install-skill] vendored skill not found at ${skillSrc}. This build is missing dist/skill — reinstall pinta-companion from npm.\n`,
    );
    process.exit(1);
  }

  const dest = join(homedir(), ".claude", "skills", "pinta");
  mkdirSync(dest, { recursive: true });
  for (const f of ["SKILL.md", "find-companion.js"]) {
    copyFileSync(join(skillSrc, f), join(dest, f));
  }

  const startCompanion = join(dest, "start-companion.js");
  writeFileSync(startCompanion, START_COMPANION_NPX, "utf8");
  try {
    chmodSync(startCompanion, 0o755);
  } catch {
    // chmod is a no-op / may EPERM on Windows — harmless, node runs it anyway.
  }

  process.stdout.write(
    `✅ Installed the /pinta skill (pinta-companion v${VERSION})\n` +
      `   ${join(dest, "SKILL.md")}\n` +
      `   ${join(dest, "find-companion.js")}\n` +
      `   ${startCompanion}  →  npx pinta-companion\n` +
      `\n` +
      `Next:\n` +
      `  1. Fully restart Claude Code (skills load at startup; /clear is not enough).\n` +
      `  2. In your project root, start the companion:  npx pinta-companion .\n` +
      `  3. Annotate in the Pinta side panel, Send to agent, then run /pinta.\n`,
  );
}

async function main(): Promise<void> {
  const rawArgs = process.argv.slice(2);

  // Subcommands are matched before the server-arg parser so `install-skill`
  // isn't mistaken for a project path.
  if (rawArgs[0] === "install-skill") {
    installSkill();
    return;
  }

  const args = parseArgs(rawArgs);
  const log = args.verbose
    ? (msg: string) => process.stderr.write(`[pinta] ${msg}\n`)
    : () => {};

  const store = new SessionStore(args.projectRoot);
  await store.restore();

  // Read URL patterns from .pinta.json so the registry entry exposes
  // them on first health check — no need to wait for an extension call.
  const projectConfig = await readProjectConfig(args.projectRoot);

  // Mutable registry-entry holder. The server reads through this on
  // every /v1/health and /v1/url-patterns POST; the CLI sets it after
  // listen() and updates it again after registry write.
  let registryEntry: RegistryEntry | null = null;

  const { port, server } = await startServer({
    port: args.port,
    autoAllocatePort: !args.portExplicit,
    store,
    log,
    getRegistryEntry: () => registryEntry,
  });
  attachWebSocket({ server, store, log });

  registryEntry = await registerEntry({
    port,
    projectRoot: args.projectRoot,
    urlPatterns: projectConfig.urlPatterns ?? [],
    version: VERSION,
  });

  process.stdout.write(
    `Pinta companion ready\n` +
      `  project: ${args.projectRoot}\n` +
      `  http:    http://127.0.0.1:${port}\n` +
      `  ws:      ws://127.0.0.1:${port}/\n` +
      (registryEntry.urlPatterns.length > 0
        ? `  patterns: ${registryEntry.urlPatterns.join(", ")}\n`
        : "  patterns: (none — add via the side panel)\n"),
  );

  let shuttingDown = false;
  const shutdown = async (signal: string) => {
    if (shuttingDown) return;
    shuttingDown = true;
    process.stderr.write(`\n[pinta] received ${signal}, shutting down\n`);
    try {
      if (registryEntry) await unregister(registryEntry.id);
    } catch (err) {
      process.stderr.write(
        `[pinta] registry cleanup failed: ${(err as Error).message}\n`,
      );
    }
    process.exit(0);
  };
  process.on("SIGINT", () => void shutdown("SIGINT"));
  process.on("SIGTERM", () => void shutdown("SIGTERM"));
  // Best-effort cleanup on uncaught exit — synchronous unlink is too
  // fiddly cross-platform, so we rely on the prune-stale path on the
  // next companion startup as the actual safety net.
}

main().catch((err) => {
  process.stderr.write(`[pinta] fatal: ${(err as Error).message}\n`);
  process.exit(1);
});
