#!/usr/bin/env bash
# Installs the Pinta skill into ~/.claude/skills/pinta/.
#
# Strategy: copy SKILL.md into place, but rewrite start-companion.js so it
# always knows where this repo lives (no matter where ~/.claude/ ends up).
#
# Usage: bash scripts/install-skill.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILL_SRC="${REPO_ROOT}/skill/pinta"
CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"
SKILL_DEST="${CLAUDE_HOME}/skills/pinta"

if [ ! -d "$SKILL_SRC" ]; then
  echo "error: skill source not found at $SKILL_SRC" >&2
  exit 1
fi

mkdir -p "$SKILL_DEST"
cp "$SKILL_SRC/SKILL.md" "$SKILL_DEST/SKILL.md"

cat > "$SKILL_DEST/start-companion.js" <<EOF
#!/usr/bin/env node
// Auto-generated by scripts/install-skill.sh. Edits here will be overwritten
// on next install. Source: ${REPO_ROOT}/skill/pinta/start-companion.js

import { spawn } from "node:child_process";
import { resolve } from "node:path";

const COMPANION_ROOT = "${REPO_ROOT}/companion";
const projectRoot = resolve(process.argv[2] ?? process.cwd());

const child = spawn(
  process.platform === "win32" ? "npm.cmd" : "npm",
  ["run", "dev", "--", "--project", projectRoot],
  { cwd: COMPANION_ROOT, stdio: "inherit" },
);

child.on("exit", (code) => process.exit(code ?? 0));
EOF
chmod +x "$SKILL_DEST/start-companion.js"

echo "installed:"
echo "  $SKILL_DEST/SKILL.md"
echo "  $SKILL_DEST/start-companion.js  →  $REPO_ROOT/companion"
echo
echo "In Claude Code, run /pinta to start the workflow."
