#!/usr/bin/env bash
# Installs the Pinta skill into ~/.claude/skills/pinta/.
#
# Strategy: copy SKILL.md into place, but rewrite start-companion.js so it
# always knows where this repo lives (no matter where ~/.claude/ ends up).
#
# Usage: bash scripts/install-skill.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# Convert MSYS/Git Bash paths (/c/...) to native Windows paths (C:/...) so
# Node's filesystem APIs can resolve them. On non-Windows this is a no-op.
if command -v cygpath >/dev/null 2>&1; then
  REPO_ROOT_NATIVE="$(cygpath -m "$REPO_ROOT")"
else
  REPO_ROOT_NATIVE="$REPO_ROOT"
fi
SKILL_SRC="${REPO_ROOT}/skill/pinta"
CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"
SKILL_DEST="${CLAUDE_HOME}/skills/pinta"

if [ ! -d "$SKILL_SRC" ]; then
  echo "error: skill source not found at $SKILL_SRC" >&2
  exit 1
fi

mkdir -p "$SKILL_DEST"
cp "$SKILL_SRC/SKILL.md" "$SKILL_DEST/SKILL.md"

cat > "$SKILL_DEST/start-companion.js" <<EOF
#!/usr/bin/env node
// Auto-generated by scripts/install-skill.sh. Edits here will be overwritten
// on next install. Source: ${REPO_ROOT_NATIVE}/skill/pinta/start-companion.js
//
// Spawns the bundled companion (no npm/tsx involved) so it works on every
// platform including Node 20+ on Windows where spawning .cmd files is fussy.

import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

const REPO_ROOT = "${REPO_ROOT_NATIVE}";
const BUNDLE = resolve(REPO_ROOT, "companion/dist/cli.cjs");
const SOURCE = resolve(REPO_ROOT, "companion/src/cli.ts");

const projectRoot = resolve(process.argv[2] ?? process.cwd());

// Prefer the prebuilt bundle. Fall back to tsx on the TS source if the
// repo hasn't been built yet (dev workflow).
let cmd, args;
if (existsSync(BUNDLE)) {
  cmd = process.execPath;
  args = [BUNDLE, "--project", projectRoot];
} else {
  const TSX = resolve(REPO_ROOT, "node_modules/tsx/dist/cli.mjs");
  if (!existsSync(TSX)) {
    process.stderr.write(
      \`[start-companion] no built bundle and no tsx — run \\\`npm install && npm run build --workspace pinta-companion\\\` in \${REPO_ROOT}\\n\`,
    );
    process.exit(1);
  }
  cmd = process.execPath;
  args = [TSX, SOURCE, "--project", projectRoot];
}

const child = spawn(cmd, args, { stdio: "inherit" });
child.on("exit", (code) => process.exit(code ?? 0));
EOF
chmod +x "$SKILL_DEST/start-companion.js"

echo "installed:"
echo "  $SKILL_DEST/SKILL.md"
echo "  $SKILL_DEST/start-companion.js  →  $REPO_ROOT/companion"
echo
echo "In Claude Code, run /pinta to start the workflow."
